version: "3.7"

volumes:
  db:

networks:
  shared:
    external:
      name: shared
  private:

services:

  net:
    image: console/net
    build:
      dockerfile: ./docker/net/Dockerfile
      context: ./
    privileged: true
    network_mode: host
    volumes:
      - /tmp/wpa_sock:/var/run/sockets
      - ./docker/net/entrypoint.sh:/entrypoint.sh:ro
      - ./docker/net/wpa_supplicant.conf.tmpl:/etc/wpa_supplicant/wpa_supplicant.conf.tmpl
      - ./docker/net/nodogsplash.conf.tmpl:/etc/nodogsplash/nodogsplash.conf.tmpl
    environment:
      - WPA_SOCKET_PATH=/var/run/sockets/wpa_supplicant
      - NDS_SOCKET_PATH=/var/run/sockets/nds
      - INTERFACE=wlx1cbfce6bc882
      - ADDRESS=192.168.102.254
      - DHCP_RANGE=192.168.102.100,192.168.102.150,1h

  back:
    image: console/back
    build:
      dockerfile: ./docker/console/Dockerfile
      target: python
      context: ./
    networks:
      - private
      - shared
    extra_hosts:
      - www.shanty.local:192.168.100.200
    volumes:
      - ./back:/app:ro
      - ./docker/console/entrypoint-app.sh:/entrypoint.sh:ro
      - /var/run/docker.sock:/var/run/sockets/docker.sock
      - db:/var/lib/console/
      - /tmp/wpa_sock:/var/run/sockets
    environment:
      - FLASK_WPA_SOCKET_PATH=/var/run/sockets/wpa_supplicant
      - FLASK_NDS_SOCKET_PATH=/var/run/sockets/nds
      - FLASK_DOCKER_SOCKET_PATH=/var/run/sockets/docker.sock
      - FLASK_SERVICE_URL=http://shanty.social/api/services/
      - FLASK_LOG_LEVEL=DEBUG
      - FLASK_DEBUG=true
      - FLASK_HOST=0.0.0.0
      - FLASK_PORT=8080
      - FLASK_DB_PATH=/var/lib/console/db.sqlite3
      - FLASK_CACHE_TYPE=flask_caching.contrib.uwsgicache.UWSGICache
      - FLASK_SHANTY_REQUEST_TOKEN_URL=http://www.shanty.local:8000/api/oauth2/token/
      - FLASK_SHANTY_API_BASE_URL=http://www.shanty.local:8000/api/

  front:
    image: console/back
    build:
      dockerfile: ./docker/console/Dockerfile
      target: node
      context: ./
    networks:
      - private
    volumes:
      - ./front:/front:ro
      - ./docker/console/entrypoint-vue.sh:/entrypoint.sh:ro
    ports:
      - 8080:8080
    environment:
      - FLASK_HOST=back
      - FLASK_PORT=8080
      - VUE_HOST=0.0.0.0
      - VUE_PORT=8080
