version: "3.7"

volumes:
  db:

networks:
  shared:
    external:
      name: shared
  private:

services:
  console-back:
    image: console/back
    build:
      dockerfile: ./docker/console/Dockerfile
      target: python
      context: ./
    network_mode: host
    extra_hosts:
      - www.shanty.local:192.168.100.200
    volumes:
      - ./back:/app:ro
      - ./docker/console/entrypoint-app.sh:/entrypoint.sh:ro
      - /var/run/docker.sock:/var/run/sockets/docker.sock
#      - /tmp/wpa_sock:/var/run/sockets
      - /tmp/certs:/var/lib/certs/
      - db:/var/lib/console/
    environment:
      - AUTH_TOKEN=abcdefghijklmnopqrstuvwxyz
      - FLASK_WPA_SOCKET_PATH=/var/run/sockets/wpa_supplicant
      - FLASK_NDS_SOCKET_PATH=/var/run/sockets/nds
      - FLASK_DOCKER_SOCKET_PATH=/var/run/sockets/docker.sock
      - FLASK_LOG_LEVEL=DEBUG
      - FLASK_DEBUG=true
      - FLASK_HOST=0.0.0.0
      - FLASK_PORT=8008
      - FLASK_DB_PATH=/var/lib/console/db.sqlite3
      - FLASK_CACHE_TYPE=flask_caching.contrib.uwsgicache.UWSGICache
      - FLASK_SHANTY_REQUEST_TOKEN_URL=http://www.shanty.local:8000/api/oauth2/token/
      - FLASK_SHANTY_API_BASE_URL=http://www.shanty.local:8000/api/
      - CERT_DIR=/var/lib/certs

  console-front:
    image: console/back
    build:
      dockerfile: ./docker/console/Dockerfile
      target: node
      context: ./
    depends_on:
      - console-back
    network_mode: host
    volumes:
      - ./front:/front:ro
      - ./docker/console/entrypoint-vue.sh:/entrypoint.sh:ro
    ports:
      - 8080:8080
    environment:
      - FLASK_HOST=console-back
      - FLASK_PORT=8008
      - VUE_HOST=0.0.0.0
      - VUE_PORT=8080
