version: "3.7"

volumes:
  db:

networks:
  shared:
    external:
      name: shared
  private:

services:

  back:
    image: console/back
    build:
      dockerfile: ./docker/console/Dockerfile
      target: python
      context: ./
    networks:
      - private
      - shared
    extra_hosts:
      - www.shanty.local:192.168.100.200
    volumes:
      - ./back:/app:ro
      - ./docker/console/entrypoint-app.sh:/entrypoint.sh:ro
      - /var/run/docker.sock:/var/run/sockets/docker.sock
      - db:/var/lib/console/
      - /tmp/wpa_sock:/var/run/sockets
    environment:
      - AUTH_TOKEN=abcdefghijklmnopqrstuvwxyz
      - FLASK_WPA_SOCKET_PATH=/var/run/sockets/wpa_supplicant
      - FLASK_NDS_SOCKET_PATH=/var/run/sockets/nds
      - FLASK_DOCKER_SOCKET_PATH=/var/run/sockets/docker.sock
      - FLASK_LOG_LEVEL=DEBUG
      - FLASK_DEBUG=true
      - FLASK_HOST=0.0.0.0
      - FLASK_PORT=8080
      - FLASK_DB_PATH=/var/lib/console/db.sqlite3
      - FLASK_CACHE_TYPE=flask_caching.contrib.uwsgicache.UWSGICache
      - FLASK_SHANTY_REQUEST_TOKEN_URL=http://www.shanty.local:8000/api/oauth2/token/
      - FLASK_SHANTY_API_BASE_URL=http://www.shanty.local:8000/api/

  front:
    image: console/back
    build:
      dockerfile: ./docker/console/Dockerfile
      target: node
      context: ./
    depends_on:
      - back
    networks:
      - private
    volumes:
      - ./front:/front:ro
      - ./docker/console/entrypoint-vue.sh:/entrypoint.sh:ro
    ports:
      - 8080:8080
    environment:
      - FLASK_HOST=back
      - FLASK_PORT=8080
      - VUE_HOST=0.0.0.0
      - VUE_PORT=8080

  ddclient:
    image: console/ddclient
    build:
      dockerfile: ./docker/ddclient/Dockerfile
      context: ./
    depends_on:
      - back
    networks:
      - private
    volumes:
      - ./docker/ddclient/entrypoint.sh:/entrypoint.sh:ro
      - ./docker/ddclient/ddclient.conf.tmpl:/etc/ddclient/ddclient.conf.tmpl:ro
    environment:
      - AUTH_TOKEN=abcdefghijklmnopqrstuvwxyz
      - CONSOLE_URL=http://back:8080

  proxy:
    image: console/proxy
    build:
      dockerfile: ./docker/proxy/Dockerfile
      context: ./
    depends_on:
      - back
    networks:
      - private
    volumes:
      - ./docker/proxy/entrypoint.sh:/entrypoint.sh:ro
      - ./docker/proxy/nginx.conf.tmpl:/etc/nginx/nginx.conf.tmpl:ro
    environment:
      - AUTH_TOKEN=abcdefghijklmnopqrstuvwxyz
      - CONSOLE_URL=http://back:8080
      - PORT=8080
