
  
# https://www.docker.com/blog/multi-arch-build-and-images-the-simple-way/
name: build docker image

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2

      - name: Test & lint
        run: |
          sudo apt install -y python3-pip
          sudo pip3 install pipenv
          make ci

      - name: Create tag
        run: echo "tag=$(date +%s)" >> $GITHUB_ENV

      - name: install buildx
        id: buildx
        uses: crazy-max/ghaction-docker-buildx@v1
        with:
          version: latest

      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: build and push
        run: |
          docker buildx build -f docker/console/Dockerfile \
            --push \
            --tag ${{secrets.DOCKER_USER}}/console:latest \
            --tag ${{secrets.DOCKER_USER}}/console:${{env.tag}} \
            --platform linux/amd64,linux/arm/v7,linux/arm64 .

      - name: Docker Hub Description
        uses: peter-evans/dockerhub-description@v2
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD_ }}
          repository: shantysocial/console

      - name: Tarball
        run: |
          make tarball

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{env.tag}}
          files: |
            output/var-lib-docker.tgz
